### ISSUE TITLE
Event Binding to Text Layer - Mark Long Words example

### ISSUE THREAD

**Issue by Huey-H** [stephanrauh/extended-pdf-viewer-showcase#936]
Based on the Text layer - Mark long words example, is there a way to bind a click/hover event to the words highlighted? I tried including the event when adding the class to the words that meet criteria but it doesn't call the function.

**Comment by Huey-H** [comment]
First of, thank you for your continuous support for this library! That is an interesting read but having trouble wrapping my head around it.

Based on the example code below, when the word is clicked, the function isn't triggered. Any suggestions on how I could force this change detection in Angular?

Example code snippet:
  private markOneLongWord(word: string): string {
    if (word.length > 6) {
      return `<div class="long-word" (click)="triggerLongWordClicked(word)">${word}</div>`;
    }
    return word;
  }

    public triggerLongWordClicked(word) {
        console.log("long word clicked: ", word);
    }

**Comment by stephanrauh** [comment]
Sorry for responding late. Just in case someone stumbles upon this ticket: `(click)` doesn't work in this case because it's plain HTML without the Angular magic. So you need to use `(onclick)`. Your method gets called, but Angular doesn't notice unless you put your method body into an `ngZone.run()` wrapper.
